services:
  mp4mp3-dev:
    container_name: mp4mp3-dev
    image: mp4mp3-dev
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        FRONTEND_BUILD_MODE: local-dev
    restart: unless-stopped
    env_file:
      - backend/.env.dev
    environment:
      AWS_PROFILE: ""
      AWS_EC2_METADATA_DISABLED: "true"
    ports:
      - "8001:3000"
    networks:
      - proxy-net
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G

  minio-dev:
    image: minio/minio:latest
    container_name: minio-server-dev
    restart: unless-stopped
    volumes:
      - minio_data_dev:/data
#    No ports exposed because I use AdGuard Home + Nginx to point a domain to an internal Docker address
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_SERVER_URL: "https://s3-mp4mp3-dev.lostmypillow.com"
      MINIO_API_CORS_ALLOW_ORIGIN: "https://mp4mp3-dev.lostmypillow.com"
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://mp4mp3-dev:3000/convert/events"
    command: server /data
    networks:
      - proxy-net
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G


  minio-init-dev:
    image: minio/mc
    depends_on:
      - minio-dev
      - mp4mp3-dev
    entrypoint: |
      /bin/sh -c "
      echo 'Waiting for MinIO dev...';
      until mc alias set localminio http://minio-dev:9000 admin password123; do
        sleep 2;
      done;
      sleep 2;
      
      # 1. Create target bucket
      mc mb --ignore-existing localminio/my-bucket;
      
      # 2. Set bucket permissions
      mc anonymous set upload localminio/my-bucket;
      
      # 3. Set Bucket CORS Policy
      cat << 'EOF' > /tmp/cors.json
      {
        \"CORSRules\": [
          {
            \"AllowedOrigins\": [\"*\"],
            \"AllowedMethods\": [\"GET\", \"PUT\", \"POST\", \"DELETE\", \"HEAD\"],
            \"AllowedHeaders\": [\"*\"],
            \"ExposeHeaders\": [\"ETag\"],
            \"MaxAgeSeconds\": 3600
          }
        ]
      }
      EOF
      mc cors set localminio/my-bucket /tmp/cors.json;
      
      # 4. Attach webhook event listener
      mc event add localminio/my-bucket arn:minio:sqs::primary:webhook --event put;
      
      # 5. Add object lifecycle rule
      mc ilm rule add --expire-days 1 localminio/my-bucket;
      
      echo 'MinIO dev initialization complete!';
      exit 0;
      "
    networks:
      - proxy-net
networks:
  proxy-net:
    external: true
volumes:
  minio_data_dev:
