services:
  mp4mp3-prod:
    container_name: mp4mp3-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.prod
    expose:
      - "3000"
    dns:
      - 192.168.50.2
      - 1.1.1.1
    networks:
        proxy-net:


networks:
    proxy-net:
      external: true
