events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream minio_s3 {
    server minio:9000;
}

server {
    listen 80;
    server_name localhost;

    # Resolver needed for Nginx to look up container names dynamically
    resolver 127.0.0.11 valid=30s;
    location /assets/ {
        proxy_pass http://minio_s3/mp4mp3-frontend/assets/;
        proxy_set_header Host minio:9000;

        # Hide S3/MinIO specific headers
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-id-2;

        # Caching for hashed static assets
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        proxy_pass http://minio_s3/mp4mp3-frontend/index.html;
        proxy_set_header Host minio:9000;

        # Prevent MinIO internal headers from leaking
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-id-2;

        # Enable SPA fallback: if resource missing in bucket, serve index.html
        error_page 404 =200 /index.html;
    }
}
}
