name: CI & Staging Deploy (PR)

on:
  push:
    branches: [ main ]

jobs:

  deploy-api:
    name: Deploy prod API to Docker
    runs-on: host
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Deploy Self-Hosted prod Containers
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          echo "Deploying updated Docker containers to prod environment..."
          docker compose -f compose.prod.yaml down
          docker compose -f compose.prod.yaml up -d --build